# Generated by Django 5.0.6 on 2024-07-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='lname',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='time',
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctortype',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
